import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";
import path from "path";

export default defineConfig({
  plugins: [react()],
  test: {
    environment: "jsdom",
    setupFiles: ["./src/test/setup.ts"],
    globals: true,
    // All three Playwright directories. They are browser suites — vitest
    // would collect their `.spec.ts` and fail on the Playwright import.
    exclude: [
      "e2e/**",
      "e2e-layout/**",
      "e2e-components/**",
      "node_modules/**",
    ],
    pool: "forks",
    teardownTimeout: 5000,
    // Above `asyncUtilTimeout` in src/test/setup.ts, so a wait that runs
    // out reports what it could not find instead of a bare test timeout.
    testTimeout: 15000,
    coverage: {
      // `istanbul`, not `v8`, and the reason is the denominator rather than
      // taste. v8 takes coverage from the engine, so it only knows about code
      // that executed: measured over four identical runs of this suite, the
      // branch *denominator* moved — 12699, 12701, 12702 — because a module
      // loaded on one run and not the next changes how much there is to
      // cover. A floor over a population that moves cannot distinguish "the
      // code got worse" from "that module did not load this time".
      //
      // istanbul instruments the AST, so the population is fixed before
      // anything runs: 21383 statements / 18946 lines / 14198 branches /
      // 5109 functions, identical across every run measured, including a run
      // with a failing test. It is also not slower than v8 here, which is the
      // opposite of the assumption this started from — but the cause is not
      // established, and both providers remap through source maps, so the
      // obvious guess is wrong. No seconds are quoted either: the two
      // measurements taken of it differ by 60% on the same machine, and CI's
      // own before/after on the job that gates is the figure that decides
      // anything. The denominator, above, is the reason for this choice.
      //
      // Instrumenting the AST also means this job runs rewritten sources while
      // `frontend (shuffled order)` runs the originals. See
      // `docs/developer-guide/testing.md` before adding coverage to that job:
      // it is the only required run of the real sources.
      provider: "istanbul",

      // Production sources, including the addon link trees under
      // `src/addons/` — which is the whole point of the directory-of-links
      // layout `setup-addons.sh` builds.
      include: ["src/**/*.{ts,tsx}"],
      exclude: [
        "**/__tests__/**",
        "**/*.test.*",
        "**/*.spec.*",
        "src/messages/**", // generated by scripts/merge-addon-messages.mjs
        "src/test/**",
        "**/*.d.ts",
      ],

      // `json-summary` is not optional: `scripts/check-coverage-denominator.mjs`
      // reads it, and that step is what earns these thresholds the right to be
      // lower bounds at all.
      reporter: ["text-summary", "json-summary"],

      // A failing run still writes the report. Without this (the default) a
      // red suite produces no summary at all, so the denominator check cannot
      // tell "a test failed" from "the population collapsed" and has to treat
      // every red build the same. Measured: with a deliberately failing test,
      // the report is still written and the population is *identical* — 515
      // files, 14198 branches — because istanbul's population does not depend
      // on what ran.
      reportOnFailure: true,

      // Four numbers, because they are four claims.
      //
      // **These are CI's figures, not a local machine's**, and the difference
      // is not slack. Coverage here is machine-dependent: measured over five
      // CI runs and twenty local ones on the same tree, CI reports 0.02-0.05
      // lower on statements, lines and functions, because some time-dependent
      // path does not execute the same way on two cores. The *denominator* is
      // identical on both (21383 / 18946 / 14198 / 5109) — istanbul fixes the
      // population before anything runs — which is what makes the two numbers
      // comparable, and what makes CI's the one a gate can be a claim about.
      //
      // So a local run showing 79.78 against a floor of 79.76 is not headroom.
      // It is a different environment's observation of the same tree.
      //
      // Set at the lowest value CI has been observed to produce, which is not
      // the lowest it can produce — one of these shipped a unit above its true
      // minimum and went red on a tree that had lost nothing.
      // `docs/developer-guide/testing.md` says what to do when one goes red,
      // and the answer is to re-run the commit, not to move the number.
      thresholds: {
        statements: 77.32,
        lines: 79.76,
        functions: 73.83,
        branches: 71.86,
      },
    },
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
    preserveSymlinks: true,
  },
});
