import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";
import path from "path";

export default defineConfig({
  plugins: [react()],
  test: {
    environment: "jsdom",
    setupFiles: ["./src/test/setup.ts"],
    globals: true,
    // All three Playwright directories. They are browser suites — vitest
    // would collect their `.spec.ts` and fail on the Playwright import.
    exclude: [
      "e2e/**",
      "e2e-layout/**",
      "e2e-components/**",
      "node_modules/**",
    ],
    pool: "forks",
    teardownTimeout: 5000,
    // Above `asyncUtilTimeout` in src/test/setup.ts, so a wait that runs
    // out reports what it could not find instead of a bare test timeout.
    testTimeout: 15000,
    coverage: {
      // `istanbul`, not `v8`, and the reason is the denominator rather than
      // taste. v8 takes coverage from the engine, so it only knows about code
      // that executed: measured over four identical runs of this suite, the
      // branch *denominator* moved — 12699, 12701, 12702 — because a module
      // loaded on one run and not the next changes how much there is to
      // cover. A floor over a population that moves cannot distinguish "the
      // code got worse" from "that module did not load this time".
      //
      // istanbul instruments the AST, so the population is fixed before
      // anything runs: 21383 statements / 18946 lines / 14198 branches /
      // 5109 functions, identical across every run measured, including a run
      // with a failing test. It is also faster here — 29.3-31.1s against
      // v8's 33.4s, against a 26.4s baseline with no coverage at all.
      provider: "istanbul",

      // Production sources, including the addon link trees under
      // `src/addons/` — which is the whole point of the directory-of-links
      // layout `setup-addons.sh` builds.
      include: ["src/**/*.{ts,tsx}"],
      exclude: [
        "**/__tests__/**",
        "**/*.test.*",
        "**/*.spec.*",
        "src/messages/**", // generated by scripts/merge-addon-messages.mjs
        "src/test/**",
        "**/*.d.ts",
      ],

      // `json-summary` is not optional: `scripts/check-coverage-denominator.mjs`
      // reads it, and that step is what earns these thresholds the right to be
      // lower bounds at all.
      reporter: ["text-summary", "json-summary"],

      // A failing run still writes the report. Without this (the default) a
      // red suite produces no summary at all, so the denominator check cannot
      // tell "a test failed" from "the population collapsed" and has to treat
      // every red build the same. Measured: with a deliberately failing test,
      // the report is still written and the population is *identical* — 515
      // files, 14198 branches — because istanbul's population does not depend
      // on what ran.
      reportOnFailure: true,

      // Four numbers, because they are four claims. The first three are
      // exactly reproducible; `branches` is the observed minimum and the two
      // files that move it are named in `docs/developer-guide/testing.md`.
      // Raise these when coverage rises; do not round them down for headroom.
      thresholds: {
        statements: 77.35,
        lines: 79.78,
        functions: 73.88,
        branches: 71.86,
      },
    },
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
    preserveSymlinks: true,
  },
});
