"use client";

import { useEffect, useRef } from "react";

const isDev = process.env.NODE_ENV !== "production";

const MARK_CLASS = "ask-citation-highlight";

/**
 * Without this normalisation, a quote generated by an LLM with
 * smart-quote post-processing never matches the source markdown that
 * contains the straight ASCII apostrophe.
 */
function normalise(text: string): string {
  return text
    .replace(/[‘’ʼʻ]/g, "'") // single quotes / apostrophes
    .replace(/[“”„«»]/g, '"') // double quotes
    .replace(/[–—―]/g, "-") // dashes
    .replace(/ /g, " ") // NBSP
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();
}

function canonChar(ch: string): string {
  // Map smart quotes / dashes to ASCII; everything else just lowercases.
  // Codepoints listed by name to keep the source readable: U+2018 / U+2019
  // (single curly quotes), U+02BC / U+02BB (modifier letter apostrophes),
  // U+201C / U+201D / U+201E / U+00AB / U+00BB (double quotes / guillemets),
  // U+2013 / U+2014 / U+2015 (en/em dashes / horizontal bar).
  if (ch === "‘" || ch === "’" || ch === "ʼ" || ch === "ʻ") {
    return "'";
  }
  if (
    ch === "“" ||
    ch === "”" ||
    ch === "„" ||
    ch === "«" ||
    ch === "»"
  ) {
    return '"';
  }
  if (ch === "–" || ch === "—" || ch === "―") {
    return "-";
  }
  return ch.toLowerCase();
}

/**
 * The mark stays in place until the user navigates away — fading it
 * out after a few seconds turned out to be confusing because users
 * scrolling the page lost track of where they had landed.
 */
export function useHighlightPassage(
  containerRef: React.RefObject<HTMLElement | null>,
  quote: string | undefined,
  ready: boolean,
): void {
  // Tracks whether we've already scrolled the user into view for the
  // current (containerRef, quote) session. The highlight is
  // re-applied on every render to survive React resetting innerHTML
  // via `dangerouslySetInnerHTML`, but the scroll must NOT repeat —
  // each repeat would yank the user back to the citation if they
  // scrolled away.
  const scrolledRef = useRef(false);

  useEffect(() => {
    scrolledRef.current = false;
  }, [quote]);

  // No dependency array on purpose. React's `dangerouslySetInnerHTML`
  // can reset the innerHTML of the container on subsequent renders,
  // wiping out any `<mark>` we inserted via `Range.surroundContents`.
  useEffect(() => {
    if (!ready) return;
    if (!quote) return;
    const container = containerRef.current;
    if (!container) return;

    const trimmed = quote.trim();
    if (trimmed.length === 0) return;

    if (container.querySelector(`mark.${MARK_CLASS}`)) return;

    if (isDev) {
      console.info("[useHighlightPassage] start", {
        containerTag: container.tagName,
        containerTextLength: container.textContent?.length ?? 0,
        quote: trimmed.slice(0, 120),
      });
    }

    const range = findPassageRange(container, trimmed);
    if (!range) {
      if (!scrolledRef.current) {
        container.scrollIntoView({ block: "start", behavior: "smooth" });
        scrolledRef.current = true;
      }
      if (isDev) {
        const haystackPreview = (container.textContent ?? "")
          .replace(/\s+/g, " ")
          .slice(0, 400);
        console.warn(
          "[useHighlightPassage] no DOM match for quote (showing top of container instead)",
          {
            quote: trimmed,
            haystackPreview,
          },
        );
      }
      return;
    }

    try {
      const marks = markRange(range);
      const first = marks[0];
      if (first && !scrolledRef.current) {
        requestAnimationFrame(() => {
          first.scrollIntoView({ block: "center", behavior: "smooth" });
        });
        scrolledRef.current = true;
      }
      if (isDev) {
        console.info("[useHighlightPassage] match wrapped in <mark>", {
          markCount: marks.length,
          textPreview: marks
            .map((m) => m.textContent ?? "")
            .join("")
            .slice(0, 80),
        });
      }
    } catch (err) {
      if (!scrolledRef.current) {
        const anchor =
          range.startContainer.nodeType === Node.ELEMENT_NODE
            ? (range.startContainer as Element)
            : range.startContainer.parentElement;
        anchor?.scrollIntoView({ block: "center", behavior: "smooth" });
        scrolledRef.current = true;
      }
      if (isDev) {
        console.warn(
          "[useHighlightPassage] could not mark the range, scrolled to anchor only",
          err,
        );
      }
    }
  });
}

interface Segment {
  node: Text;
  start: number;
  end: number;
}

/**
 * `Range.surroundContents` throws as soon as an endpoint sits inside an
 * element the range only partially covers — which is every quote that
 * crosses a syntax-highlighting token or a paragraph. Wrapping each
 * intersected text node on its own has no such restriction.
 */
function markRange(range: Range): HTMLElement[] {
  const segments = collectSegments(range);

  // Splitting mutates the nodes, so the offsets are resolved first and
  // each node is split from its tail inwards.
  return segments.map(({ node, start, end }) => {
    if (end < node.length) node.splitText(end);
    const target = start > 0 ? node.splitText(start) : node;
    const mark = document.createElement("mark");
    mark.className = MARK_CLASS;
    target.parentNode?.insertBefore(mark, target);
    mark.appendChild(target);
    return mark;
  });
}

function collectSegments(range: Range): Segment[] {
  const { startContainer, startOffset, endContainer, endOffset } = range;
  if (
    startContainer.nodeType !== Node.TEXT_NODE ||
    endContainer.nodeType !== Node.TEXT_NODE
  ) {
    throw new Error("markRange expects text-node endpoints");
  }

  if (startContainer === endContainer) {
    const node = startContainer as Text;
    return startOffset < endOffset
      ? [{ node, start: startOffset, end: endOffset }]
      : [];
  }

  const root =
    range.commonAncestorContainer.nodeType === Node.TEXT_NODE
      ? range.commonAncestorContainer.parentNode
      : range.commonAncestorContainer;
  if (!root) return [];

  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  const segments: Segment[] = [];
  let inside = false;
  while (walker.nextNode()) {
    const node = walker.currentNode as Text;
    if (node === startContainer) {
      inside = true;
      if (startOffset < node.length) {
        segments.push({ node, start: startOffset, end: node.length });
      }
      continue;
    }
    if (node === endContainer) {
      if (endOffset > 0) segments.push({ node, start: 0, end: endOffset });
      return segments;
    }
    if (inside && node.length > 0) {
      segments.push({ node, start: 0, end: node.length });
    }
  }
  return segments;
}

interface NodeEntry {
  node: Text;
  start: number;
  prevWasSpaceAtEntry: boolean;
}

function findPassageRange(container: HTMLElement, needle: string): Range | null {
  const normNeedle = normalise(needle);
  if (normNeedle.length === 0) return null;

  const walker = document.createTreeWalker(container, NodeFilter.SHOW_TEXT);
  const nodes: NodeEntry[] = [];
  let buffer = "";
  let prevWasSpace = true; // leading whitespace at root collapses away
  while (walker.nextNode()) {
    const node = walker.currentNode as Text;
    nodes.push({ node, start: buffer.length, prevWasSpaceAtEntry: prevWasSpace });
    const raw = node.nodeValue ?? "";
    // We normalise the haystack character-by-character (collapsing
    // whitespace) but also map the same canonical-punctuation set as
    // the needle. The per-char transform must match `normalise`
    // exactly or matching becomes asymmetric.
    for (let i = 0; i < raw.length; i++) {
      const ch = raw[i];
      const isSpace = ch === " " || ch === " " || /\s/.test(ch);
      if (isSpace) {
        if (!prevWasSpace) {
          buffer += " ";
          prevWasSpace = true;
        }
      } else {
        buffer += canonChar(ch);
        prevWasSpace = false;
      }
    }
  }

  let hit = buffer.indexOf(normNeedle);
  let needleLen = normNeedle.length;

  if (hit < 0) {
    // Fallback A: shrink from the tail at word boundaries. Handles
    // LLM paraphrase at the end of the quote.
    const tokens = normNeedle.split(" ");
    while (tokens.length > 3) {
      tokens.pop();
      const probe = tokens.join(" ");
      const probeHit = buffer.indexOf(probe);
      if (probeHit >= 0) {
        hit = probeHit;
        needleLen = probe.length;
        break;
      }
    }
  }

  if (hit < 0) {
    // Fallback B: try increasingly short character prefixes. Handles
    // mid-quote divergence (e.g. LLM rephrased a clause). The lower
    // bound (25 chars) is short enough to land near any cited passage
    // but long enough that random short phrases don't false-match.
    for (const len of [60, 40, 25]) {
      if (normNeedle.length <= len) continue;
      const probe = normNeedle.slice(0, len);
      const probeHit = buffer.indexOf(probe);
      if (probeHit >= 0) {
        hit = probeHit;
        needleLen = probe.length;
        break;
      }
    }
  }

  if (hit < 0) {
    // Fallback C: contiguous N-token sliding window. RAG-grounded
    // citations almost always carry at least one verbatim phrase
    // ~4-7 words long. 4 words is the floor: shorter windows have too
    // high a false-match rate ("of the system" matches anything).
    const tokens = normNeedle.split(" ").filter((t) => t.length > 0);
    outer: for (const winLen of [7, 6, 5, 4]) {
      if (tokens.length < winLen) continue;
      for (let i = 0; i <= tokens.length - winLen; i++) {
        const probe = tokens.slice(i, i + winLen).join(" ");
        // Skip ultra-short probes even at the configured win size
        // (purely-stopword windows have lengths well below useful).
        if (probe.length < 16) continue;
        const probeHit = buffer.indexOf(probe);
        if (probeHit >= 0) {
          hit = probeHit;
          needleLen = probe.length;
          break outer;
        }
      }
    }
  }

  if (hit < 0) {
    // Fallback D: character-based sliding window. Required for
    // languages without inter-word whitespace (Japanese / Chinese /
    // Thai), where Fallback C's `split(" ")` yields one giant token
    // and so never engages. Once we find any verbatim run of ~12+
    // characters, expand greedily on both sides to cover the longest
    // common stretch — that produces a more visually satisfying
    // highlight than just the bare window. The 12-char floor is
    // empirical: shorter common runs in CJK frequently false-match
    // (e.g. "ことがあります" appears unrelated places).
    outer: for (const winLen of [30, 20, 15, 12]) {
      if (normNeedle.length < winLen) continue;
      for (let i = 0; i + winLen <= normNeedle.length; i++) {
        const probe = normNeedle.slice(i, i + winLen);
        const probeHit = buffer.indexOf(probe);
        if (probeHit >= 0) {
          let lo = probeHit;
          let hi = probeHit + winLen;
          let nLo = i;
          let nHi = i + winLen;
          while (
            lo > 0 &&
            nLo > 0 &&
            buffer[lo - 1] === normNeedle[nLo - 1]
          ) {
            lo -= 1;
            nLo -= 1;
          }
          while (
            hi < buffer.length &&
            nHi < normNeedle.length &&
            buffer[hi] === normNeedle[nHi]
          ) {
            hi += 1;
            nHi += 1;
          }
          hit = lo;
          needleLen = hi - lo;
          break outer;
        }
      }
    }
  }

  if (hit < 0) return null;

  const startLoc = locateOffset(nodes, hit);
  const endLoc = locateOffset(nodes, hit + needleLen);
  if (!startLoc || !endLoc) return null;

  const range = document.createRange();
  try {
    range.setStart(startLoc.node, startLoc.localOffset);
    range.setEnd(endLoc.node, endLoc.localOffset);
  } catch {
    return null;
  }
  return range;
}

function locateOffset(
  nodes: NodeEntry[],
  target: number,
): { node: Text; localOffset: number } | null {
  for (let n = 0; n < nodes.length; n++) {
    const entry = nodes[n];
    const next = nodes[n + 1];
    const nodeNormStart = entry.start;
    const nodeNormEnd = next ? next.start : Number.POSITIVE_INFINITY;
    if (target < nodeNormStart) return null;
    if (target > nodeNormEnd) continue;

    const raw = entry.node.nodeValue ?? "";
    let normIdx = nodeNormStart;
    let prevWasSpace = entry.prevWasSpaceAtEntry;

    if (normIdx === target) {
      return { node: entry.node, localOffset: 0 };
    }

    for (let i = 0; i < raw.length; i++) {
      const ch = raw[i];
      const isSpace = /\s/.test(ch);
      if (isSpace) {
        if (!prevWasSpace) {
          normIdx += 1;
          prevWasSpace = true;
        }
      } else {
        normIdx += 1;
        prevWasSpace = false;
      }
      if (normIdx >= target) {
        return { node: entry.node, localOffset: i + 1 };
      }
    }
  }
  return null;
}
