"use client";

import { useEffect, useRef } from "react";

const isDev = process.env.NODE_ENV !== "production";

const MARK_CLASS = "ask-citation-highlight";

/**
 * Normalise text for fuzzy matching against the rendered DOM:
 *  - lowercase
 *  - collapse whitespace runs to a single space
 *  - canonicalise the punctuation that LLM outputs reliably mangle
 *    (smart quotes / curly apostrophe / em-dash / NBSP) to ASCII
 *
 * Without this normalisation, a quote like ``"It's a hot day."``
 * generated by an LLM with smart-quote post-processing never matches
 * the source markdown that contains the straight ASCII apostrophe.
 * That's the most common reason highlight silently no-ops.
 */
function normalise(text: string): string {
  return text
    .replace(/[‘’ʼʻ]/g, "'") // single quotes / apostrophes
    .replace(/[“”„«»]/g, '"') // double quotes
    .replace(/[–—―]/g, "-") // dashes
    .replace(/ /g, " ") // NBSP
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();
}

/**
 * Per-character canonicalisation that mirrors `normalise` but for the
 * incremental walker path. Whitespace is handled by the caller.
 */
function canonChar(ch: string): string {
  // Map smart quotes / dashes to ASCII; everything else just lowercases.
  // Codepoints listed by name to keep the source readable: U+2018 / U+2019
  // (single curly quotes), U+02BC / U+02BB (modifier letter apostrophes),
  // U+201C / U+201D / U+201E / U+00AB / U+00BB (double quotes / guillemets),
  // U+2013 / U+2014 / U+2015 (en/em dashes / horizontal bar).
  if (ch === "‘" || ch === "’" || ch === "ʼ" || ch === "ʻ") {
    return "'";
  }
  if (
    ch === "“" ||
    ch === "”" ||
    ch === "„" ||
    ch === "«" ||
    ch === "»"
  ) {
    return '"';
  }
  if (ch === "–" || ch === "—" || ch === "―") {
    return "-";
  }
  return ch.toLowerCase();
}

/**
 * Find a passage inside a container, wrap the first occurrence in a
 * `<mark>` element, and scroll it into view. Used by text / markdown
 * previewers when arriving from an intelligence Ask citation card —
 * the citation only carries the quote string, so we resolve the
 * concrete location in the rendered DOM here.
 *
 * Matching strategy (ordered, first-hit wins):
 *  1. Full quote verbatim (after `normalise`).
 *  2. Word-boundary suffix shrink — drop trailing tokens until 3
 *     remain. Handles LLM tail paraphrase.
 *  3. Character prefix — try the first 60 / 40 / 25 chars of the
 *     normalised quote. Handles cases where punctuation in the middle
 *     of the quote diverged from the source (e.g. LLM dropped a
 *     parenthetical).
 *
 * Even when matching fails, we fall back to scrolling the container
 * into view at the top so the user is at least put in front of the
 * cited file rather than wherever the page happened to be.
 *
 * The match is wrapped in a `<mark class="ask-citation-highlight">`.
 * The mark stays in place until the user navigates away — fading it
 * out after a few seconds turned out to be confusing because users
 * scrolling the page lost track of where they had landed.
 */
export function useHighlightPassage(
  containerRef: React.RefObject<HTMLElement | null>,
  quote: string | undefined,
  ready: boolean,
): void {
  // Tracks whether we've already scrolled the user into view for the
  // current (containerRef, quote) session. The highlight is
  // re-applied on every render to survive React resetting innerHTML
  // via `dangerouslySetInnerHTML`, but the scroll must NOT repeat —
  // each repeat would yank the user back to the citation if they
  // scrolled away.
  const scrolledRef = useRef(false);

  // Reset scroll state when the quote actually changes (new citation
  // navigation). Without this, navigating to a different citation in
  // the same session would skip the scroll because the ref stayed
  // true.
  useEffect(() => {
    scrolledRef.current = false;
  }, [quote]);

  // No dependency array on purpose. React's `dangerouslySetInnerHTML`
  // can reset the innerHTML of the container on subsequent renders,
  // wiping out any `<mark>` we inserted via `Range.surroundContents`.
  // We re-run after every render and re-apply the mark when missing,
  // bailing out cheaply when it's still in place. This is the same
  // shape as MarkdownPreview's own mermaid-rehydrate effect — both
  // are reconciliation-safe DOM mutations layered on top of an
  // innerHTML-managed body.
  useEffect(() => {
    if (!ready) return;
    if (!quote) return;
    const container = containerRef.current;
    if (!container) return;

    const trimmed = quote.trim();
    if (trimmed.length === 0) return;

    // If a previous render's `<mark>` survived (innerHTML was not
    // reset), leave it alone — re-wrapping would unnecessarily
    // detach/reattach text nodes.
    if (container.querySelector(`mark.${MARK_CLASS}`)) return;

    if (isDev) {
      console.info("[useHighlightPassage] start", {
        containerTag: container.tagName,
        containerTextLength: container.textContent?.length ?? 0,
        quote: trimmed.slice(0, 120),
      });
    }

    const range = findPassageRange(container, trimmed);
    if (!range) {
      // Couldn't pin the exact passage — at least scroll the container
      // into view so the user lands on the cited file rather than
      // wherever the previous scroll position was. Only do this once
      // per quote so the user can scroll away without being yanked
      // back on every render.
      if (!scrolledRef.current) {
        container.scrollIntoView({ block: "start", behavior: "smooth" });
        scrolledRef.current = true;
      }
      if (isDev) {
        // Surface a generous slice of the haystack and the full quote
        // so we can compare them side-by-side when diagnosing
        // user-reported "highlight didn't fire" cases. The needle
        // typically diverges from the source in subtle ways
        // (paraphrase, translation drift) that are obvious only when
        // both strings are visible.
        const haystackPreview = (container.textContent ?? "")
          .replace(/\s+/g, " ")
          .slice(0, 400);
        console.warn(
          "[useHighlightPassage] no DOM match for quote (showing top of container instead)",
          {
            quote: trimmed,
            haystackPreview,
          },
        );
      }
      return;
    }

    try {
      const m = document.createElement("mark");
      m.className = MARK_CLASS;
      range.surroundContents(m);
      // Scroll only on the first successful wrap per quote. Subsequent
      // re-applications (when React reset innerHTML and we rebuilt
      // the mark) must NOT scroll — the user might already be
      // reading further down the file by then.
      if (!scrolledRef.current) {
        requestAnimationFrame(() => {
          m.scrollIntoView({ block: "center", behavior: "smooth" });
        });
        scrolledRef.current = true;
      }
      if (isDev) {
        console.info("[useHighlightPassage] match wrapped in <mark>", {
          textPreview: m.textContent?.slice(0, 80),
        });
      }
    } catch (err) {
      // surroundContents fails when the range crosses element
      // boundaries (e.g. the quote spans two paragraphs). Fall back to
      // scrolling the start of the range into view without wrapping —
      // the user still lands on the right spot, just without a
      // visible highlight.
      if (!scrolledRef.current) {
        const anchor =
          range.startContainer.nodeType === Node.ELEMENT_NODE
            ? (range.startContainer as Element)
            : range.startContainer.parentElement;
        anchor?.scrollIntoView({ block: "center", behavior: "smooth" });
        scrolledRef.current = true;
      }
      if (isDev) {
        console.warn(
          "[useHighlightPassage] surroundContents failed (range crosses element boundary), scrolled to anchor only",
          err,
        );
      }
    }
  });
}

interface NodeEntry {
  node: Text;
  // Normalized-buffer index at the moment we entered this node.
  start: number;
  // Whether the previous emitted character (across the whole walk) was
  // whitespace at the moment we entered this node. Captured so the
  // offset-locator can replay the same collapse logic deterministically.
  prevWasSpaceAtEntry: boolean;
}

/**
 * Walk text nodes inside `container` and return a Range covering the
 * first occurrence of `needle`. Returns null when no match is found.
 *
 * The rendered DOM contains soft line breaks, indentation, and inline
 * element boundaries that don't match the quote string verbatim.
 * Normalisation here:
 *  - lowercase
 *  - collapse runs of whitespace to a single space
 *
 * Both the haystack (built by walking text nodes) and the needle are
 * normalised the same way. To recover the original DOM Range we keep
 * a per-node bookkeeping array and replay the collapse during offset
 * lookup.
 */
function findPassageRange(container: HTMLElement, needle: string): Range | null {
  const normNeedle = normalise(needle);
  if (normNeedle.length === 0) return null;

  const walker = document.createTreeWalker(container, NodeFilter.SHOW_TEXT);
  const nodes: NodeEntry[] = [];
  let buffer = "";
  let prevWasSpace = true; // leading whitespace at root collapses away
  while (walker.nextNode()) {
    const node = walker.currentNode as Text;
    nodes.push({ node, start: buffer.length, prevWasSpaceAtEntry: prevWasSpace });
    const raw = node.nodeValue ?? "";
    // We normalise the haystack character-by-character (collapsing
    // whitespace) but also map the same canonical-punctuation set as
    // the needle. The per-char transform must match `normalise`
    // exactly or matching becomes asymmetric.
    for (let i = 0; i < raw.length; i++) {
      const ch = raw[i];
      const isSpace = ch === " " || ch === " " || /\s/.test(ch);
      if (isSpace) {
        if (!prevWasSpace) {
          buffer += " ";
          prevWasSpace = true;
        }
      } else {
        buffer += canonChar(ch);
        prevWasSpace = false;
      }
    }
  }

  let hit = buffer.indexOf(normNeedle);
  let needleLen = normNeedle.length;

  if (hit < 0) {
    // Fallback A: shrink from the tail at word boundaries. Handles
    // LLM paraphrase at the end of the quote.
    const tokens = normNeedle.split(" ");
    while (tokens.length > 3) {
      tokens.pop();
      const probe = tokens.join(" ");
      const probeHit = buffer.indexOf(probe);
      if (probeHit >= 0) {
        hit = probeHit;
        needleLen = probe.length;
        break;
      }
    }
  }

  if (hit < 0) {
    // Fallback B: try increasingly short character prefixes. Handles
    // mid-quote divergence (e.g. LLM rephrased a clause). The lower
    // bound (25 chars) is short enough to land near any cited passage
    // but long enough that random short phrases don't false-match.
    for (const len of [60, 40, 25]) {
      if (normNeedle.length <= len) continue;
      const probe = normNeedle.slice(0, len);
      const probeHit = buffer.indexOf(probe);
      if (probeHit >= 0) {
        hit = probeHit;
        needleLen = probe.length;
        break;
      }
    }
  }

  if (hit < 0) {
    // Fallback C: contiguous N-token sliding window. The LLM may have
    // paraphrased the head, tail, AND middle, but RAG-grounded
    // citations almost always carry at least one verbatim phrase
    // ~4-7 words long. We split the needle into every contiguous
    // window of length N and search each against the haystack,
    // shrinking N from 7 down to 4. The first hit wins — we don't
    // try to merge nearby hits because that risks pinning unrelated
    // content. 4 words is the floor: shorter windows have too high a
    // false-match rate ("of the system" matches anything).
    const tokens = normNeedle.split(" ").filter((t) => t.length > 0);
    outer: for (const winLen of [7, 6, 5, 4]) {
      if (tokens.length < winLen) continue;
      for (let i = 0; i <= tokens.length - winLen; i++) {
        const probe = tokens.slice(i, i + winLen).join(" ");
        // Skip ultra-short probes even at the configured win size
        // (purely-stopword windows have lengths well below useful).
        if (probe.length < 16) continue;
        const probeHit = buffer.indexOf(probe);
        if (probeHit >= 0) {
          hit = probeHit;
          needleLen = probe.length;
          break outer;
        }
      }
    }
  }

  if (hit < 0) {
    // Fallback D: character-based sliding window. Required for
    // languages without inter-word whitespace (Japanese / Chinese /
    // Thai), where Fallback C's `split(" ")` yields one giant token
    // and so never engages. Once we find any verbatim run of ~12+
    // characters, expand greedily on both sides to cover the longest
    // common stretch — that produces a more visually satisfying
    // highlight than just the bare window. The 12-char floor is
    // empirical: shorter common runs in CJK frequently false-match
    // (e.g. "ことがあります" appears unrelated places).
    outer: for (const winLen of [30, 20, 15, 12]) {
      if (normNeedle.length < winLen) continue;
      for (let i = 0; i + winLen <= normNeedle.length; i++) {
        const probe = normNeedle.slice(i, i + winLen);
        const probeHit = buffer.indexOf(probe);
        if (probeHit >= 0) {
          let lo = probeHit;
          let hi = probeHit + winLen;
          let nLo = i;
          let nHi = i + winLen;
          while (
            lo > 0 &&
            nLo > 0 &&
            buffer[lo - 1] === normNeedle[nLo - 1]
          ) {
            lo -= 1;
            nLo -= 1;
          }
          while (
            hi < buffer.length &&
            nHi < normNeedle.length &&
            buffer[hi] === normNeedle[nHi]
          ) {
            hi += 1;
            nHi += 1;
          }
          hit = lo;
          needleLen = hi - lo;
          break outer;
        }
      }
    }
  }

  if (hit < 0) return null;

  const startLoc = locateOffset(nodes, hit);
  const endLoc = locateOffset(nodes, hit + needleLen);
  if (!startLoc || !endLoc) return null;

  const range = document.createRange();
  try {
    range.setStart(startLoc.node, startLoc.localOffset);
    range.setEnd(endLoc.node, endLoc.localOffset);
  } catch {
    return null;
  }
  return range;
}

/**
 * Translate a normalized-buffer position back into a (textNode, local
 * offset) pair by replaying the whitespace-collapse against the
 * original text.
 */
function locateOffset(
  nodes: NodeEntry[],
  target: number,
): { node: Text; localOffset: number } | null {
  for (let n = 0; n < nodes.length; n++) {
    const entry = nodes[n];
    const next = nodes[n + 1];
    const nodeNormStart = entry.start;
    // Where the *next* node started (or buffer end for the last node).
    const nodeNormEnd = next ? next.start : Number.POSITIVE_INFINITY;
    if (target < nodeNormStart) return null;
    if (target > nodeNormEnd) continue;

    // Walk this node's raw text and find the local offset that lands
    // on (or just after) the target normalized index.
    const raw = entry.node.nodeValue ?? "";
    let normIdx = nodeNormStart;
    let prevWasSpace = entry.prevWasSpaceAtEntry;

    if (normIdx === target) {
      return { node: entry.node, localOffset: 0 };
    }

    for (let i = 0; i < raw.length; i++) {
      const ch = raw[i];
      const isSpace = /\s/.test(ch);
      if (isSpace) {
        if (!prevWasSpace) {
          normIdx += 1;
          prevWasSpace = true;
        }
      } else {
        normIdx += 1;
        prevWasSpace = false;
      }
      if (normIdx >= target) {
        return { node: entry.node, localOffset: i + 1 };
      }
    }
  }
  return null;
}
